# Generated by Django 3.1.2 on 2020-11-03 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manger', '0002_auto_20201103_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesesmanger',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 16, 37, 17, 920655)),
        ),
        migrations.AlterField(
            model_name='salesesmanger',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
