# Generated by Django 3.1.2 on 2020-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manger', '0005_remove_salesesmanger_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesesmanger',
            name='salesCode',
            field=models.SmallIntegerField(max_length=5, unique=True),
        ),
    ]
