# Generated by Django 3.1.2 on 2020-11-15 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayedProducts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 22, 6, 5, 351926, tzinfo=utc))),
                ('productID', models.TextField()),
                ('opNum', models.IntegerField()),
                ('price', models.TextField()),
                ('discound', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('total', models.TextField()),
                ('payeduser', models.IntegerField()),
                ('count', models.TextField()),
                ('lastTotal', models.DecimalField(decimal_places=2, default=models.TextField(), max_digits=10000)),
            ],
        ),
    ]
