# Generated by Django 3.2.2 on 2021-05-08 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payedProducts', '0002_auto_20201116_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payedproducts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 37, 46, 748997, tzinfo=utc)),
        ),
    ]
