# Generated by Django 3.1.2 on 2020-11-13 00:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receiptmanger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptsmanger',
            name='catename',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciptsmanger',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 13, 0, 51, 21, 462464, tzinfo=utc)),
        ),
    ]
