# Generated by Django 3.1.2 on 2020-11-13 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receiptmanger', '0003_auto_20201113_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptsmanger',
            name='json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciptsmanger',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 13, 22, 10, 32, 747867, tzinfo=utc)),
        ),
    ]
