# Generated by Django 3.1.2 on 2020-11-13 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receiptmanger', '0005_auto_20201114_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptsmanger',
            name='addeduser',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciptsmanger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 22, 49, 43, 896228, tzinfo=utc)),
        ),
    ]
