# Generated by Django 3.1.2 on 2020-11-13 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receiptmanger', '0006_auto_20201114_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptsmanger',
            name='total',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reciptsmanger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 22, 57, 9, 969686, tzinfo=utc)),
        ),
    ]
