# Generated by Django 3.1.2 on 2020-11-13 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receiptmanger', '0007_auto_20201114_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciptsmanger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 23, 3, 17, 939309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reciptsmanger',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10000),
        ),
    ]
